Lecture 22 Network Centrality
tools4ds/DS701-Course-Notes pull request #187
Opened 2024-11-10 23:03 UTC by sladenheim

Summary of the PR

- Format slides
- I elaborated more on the definitions of 
- Revised slides on eigenvector centrality
- Add colorbars and legends to all of the network plots
- Edited adjacency graph to show 1's and 0's

2024-11-12 23:08 UTC, trgardos requested changes
oof. this is a pretty heavy lecture. I'm inclined to not go into all the details and derviations and maybe make up our time to fit it in the time remaining wed/thurs. what do you think?

2024-11-12 23:08 UTC, trgardos commented on ds701_book/22-Networks-II-Centrality-Clustering.qmd
> +\text{closeness}(i) = \frac{1}{\sum_{j \in V} d(i,j)}.
I suppose it is the set of all vertices, right?

2024-11-12 23:37 UTC, sladenheim commented on ds701_book/22-Networks-II-Centrality-Clustering.qmd
> +\text{closeness}(i) = \frac{1}{\sum_{j \in V} d(i,j)}.
Yes.

2024-11-12 23:38 UTC, sladenheim commented on ds701_book/22-Networks-II-Centrality-Clustering.qmd
> +x_i = \frac{1}{\lambda} \sum_{j=1}^{n} A_{ij} x_j,
Fine with that.

2024-11-12 23:39 UTC, sladenheim commented
I am fine with covering a few of the topics (maybe only 1 of the centrality measures) as opposed to all of it. I think we would only get through a small portion of this lecture.

2024-11-13 00:48 UTC, trgardos commented
indeed, we could put conditional display around the derivations and leave that in web course notes and then just show results and examples in the slides.

2024-11-13 01:18 UTC, sladenheim commented on ds701_book/22-Networks-II-Centrality-Clustering.qmd
> +where $\mathbf{x}$ is the eigenvector corresponding to the the eigenvalue $\lambda$ of the adjacency matrix $\mathbf{A}$. The eigenvector $\mathbf{x}$ gives the centrality scores for all nodes in the
Under the condition of a graph being strongly connected (the adjacency matrix is then irreducible), the Perron Frobenius theorem will imply that the eigenvector is unique https://nhigham.com/2021/07/13/what-is-the-perron-frobenius-theorem/. 

I agree we can make this less "theoretical".

2024-11-13 15:24 UTC, sladenheim commented on ds701_book/22-Networks-II-Centrality-Clustering.qmd
> +\text{closeness}(i) = \frac{1}{\sum_{j \in V} d(i,j)}.
I added a line saying $G=(V, E)$ to make it clearer that $V$ is the set of nodes.

2024-11-13 15:25 UTC, sladenheim commented on ds701_book/22-Networks-II-Centrality-Clustering.qmd
> +x_i = \frac{1}{\lambda} \sum_{j=1}^{n} A_{ij} x_j,
I added a line about how $x_i$ is proportional to a sum of the nodes that it is actually connected to. Let me know if that works for you.

2024-11-13 15:27 UTC, sladenheim commented on ds701_book/22-Networks-II-Centrality-Clustering.qmd
> +As a more detailed example, we can ask whether this definition of *prestige* applies to NCAA Division 1A football teams, based on who they play against. Remember this data is from 2000.
I commented out this example. It feels randomly thrown in and I feel it distracts from the point we are trying to make about the karate example.

2024-11-13 15:27 UTC, sladenheim commented on ds701_book/22-Networks-II-Centrality-Clustering.qmd
> +Let's compare the three versions of centrality we've looked at so far.
I made a comment saying we have highlighted 2 important individuals in the plot who are the teacher and club president.

2024-11-13 15:28 UTC, sladenheim commented on ds701_book/22-Networks-II-Centrality-Clustering.qmd
> +![](figs/L23-max-flow-soviet-rail-1955.png){fig-align="center" width="75%"}
I added more context about what this figure is. The US government was looking where they could effectively halt transportation of soviet materials!

2024-11-13 15:28 UTC, sladenheim commented
I made some revisions to the request. I think we should aim to just cover the centrality measures. We can then tell them to read about min-cut and balanced cuts on their own.

2024-11-13 20:41 UTC, sladenheim commented on ds701_book/22-Networks-II-Centrality-Clustering.qmd
> +where $\mathbf{x}$ is the eigenvector corresponding to the the eigenvalue $\lambda$ of the adjacency matrix $\mathbf{A}$. The eigenvector $\mathbf{x}$ gives the centrality scores for all nodes in the
I added an additional slide for the geometric interpretation of eigenvector centrality.

2024-11-13 21:18 UTC, trgardos approved these changes

2024-11-13 21:18 UTC, merged